### ISSUE TITLE
Programmatically scroll to previous/next week

### ISSUE THREAD

**Issue by a-philipp** [Magnuti/Weekly-Date-Picker#4]
It would be nice if there was an option to scroll to another week programmatically, if, for example, selectedDay goes outside the current week.

**Comment by Magnuti** [comment]
Ah yes, this should be possible @a-philipp. I'll create a fix for it soon.

**Comment by Magnuti** [comment]
Okay @a-philipp I have a solution to your problem!

As mentioned here https://github.com/flutter/flutter/issues/48110#issuecomment-570496275 we can pass a new `UniqueKey` as `key` to the `WeeklyDatePicker` widget. This causes `initState` to re-run, which causes the widget to jump to the new `selectedDay`.

For example, in the code below when we press the text button we jump to the next week.
```dart
class _MyHomePageState extends State<MyHomePage> {
  DateTime _selectedDay = DateTime.now();
  UniqueKey _key = UniqueKey();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Column(
        children: [
          WeeklyDatePicker(
            key: _key, // The unique key
            selectedDay: _selectedDay,
            changeDay: (value) => setState(() {
              _selectedDay = value;
            }),
          ),
          TextButton(
            onPressed: () {
              setState(() {
                _key = UniqueKey(); // Set a new unique key
                _selectedDay = _selectedDay.add(Duration(days: 7));
              });
            },
            child: Text('Go to next week'),
          ),
        ],
      ),
    );
  }
}
```

I hope this was helpful, otherwise let me know!

**Comment by a-philipp** [comment]
Thanks, it worked!
